- name: Basic Content Switching Configuration
  hosts: azure_netscaler
  gather_facts: false
  tasks:
    - name: Enable LB CS features
      delegate_to: localhost
      netscaler.adc.nsfeature:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: enabled
        feature:
          - CS
          - LB
    - name: Add a service named svc-red-server
      delegate_to: localhost
      netscaler.adc.service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        name: svc-red-server
        ipaddress: "{{ red_ip }}"
        servicetype: HTTP
        port: 80
    - name: Add a service named svc-green-server
      delegate_to: localhost
      netscaler.adc.service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        name: svc-green-server
        ipaddress: "{{ green_ip }}"
        servicetype: HTTP
        port: 80
    - name: Add an HTTP lb vserver named lb-red-server 
      delegate_to: localhost
      netscaler.adc.lbvserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        name: lb-red-server
        servicetype: HTTP
        lbvserver_service_binding:
          mode: desired # desired | bind | unbind
          binding_members:
            - name: lb-red-server
              servicename: svc-red-server
    - name: Add an HTTP lb vserver named lb-green-server
      delegate_to: localhost
      netscaler.adc.lbvserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        name: lb-green-server
        servicetype: HTTP
        lbvserver_service_binding:
          mode: desired # desired | bind | unbind
          binding_members:
            - name: lb-green-server
              servicename: svc-green-server
    - name: Add a cs action csaction-red-server to target LB vserver lb-red-server
      delegate_to: localhost
      netscaler.adc.csaction:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        name: csaction-red-server
        targetlbvserver: lb-red-server
    - name: Add a cs action csaction-green-server to target LB vserver lb-green-server
      delegate_to: localhost
      netscaler.adc.csaction:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        name: csaction-green-server
        targetlbvserver: lb-green-server
    - name: Add a cs policy named cspolicy-red-server with a rule that checks is csaction-red-server should be performed
      delegate_to: localhost
      netscaler.adc.cspolicy:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        policyname: cspolicy-red-server
        rule: "HTTP.REQ.URL.SET_TEXT_MODE(IGNORECASE).STARTSWITH(\"/red\")"
        action: csaction-red-server
    - name: Add a cs policy named cspolicy-green-server with a rule that checks is csaction-green-server should be performed
      delegate_to: localhost
      netscaler.adc.cspolicy:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        policyname: cspolicy-green-server
        rule: "HTTP.REQ.URL.SET_TEXT_MODE(IGNORECASE).STARTSWITH(\"/green\")"
        action: csaction-green-server
    - name: Add an HTTP cs vserver named demo-csvserver and bind the above policies to it
      delegate_to: localhost
      netscaler.adc.csvserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        nitro_protocol: "{{ nitro_protocol }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        name: demo-csvserver
        servicetype: HTTP
        ipv46: "{{ vip_ip }}"
        port: 80
        csvserver_cspolicy_binding:
          mode: desired # desired | bind | unbind
          binding_members:
            - name: demo-csvserver
              policyname: cspolicy-red-server
              priority: 100
            - name: demo-csvserver
              policyname: cspolicy-green-server
              priority: 110
